<xml>
<ToUserName><![CDATA[${ToUserName}]]></ToUserName>
<FromUserName><![CDATA[${FromUserName}]]></FromUserName>
<CreateTime>${CreateTime}</CreateTime>
<MsgType><![CDATA[${MsgType}]]></MsgType>
<ArticleCount>${ArticleCount}</ArticleCount>
<Articles>
<item>
<Title><![CDATA[${Title}]]></Title> 
<Description><![CDATA[${Description}]]></Description>
<PicUrl><![CDATA[${PicUrl}]]></PicUrl>
<Url><![CDATA[${Url}]]></Url>
</item>
</Articles>
</xml>