<xml>
<ToUserName><![CDATA[${ToUserName}]]></ToUserName>
<FromUserName><![CDATA[${FromUserName}]]></FromUserName>
<CreateTime>${CreateTime}</CreateTime>
<MsgType><![CDATA[${MsgType}]]></MsgType>
<Image>
<MediaId><![CDATA[${MediaId}]]></MediaId>
</Image>
</xml>